name: Tests

on:
  workflow_run:
    workflows: ["Docker"]
    branches: [ "master" ]
    types:
      - completed
jobs:
  ci:
    runs-on: ubuntu-latest
    services:
      php:
        image: ghcr.io/painfull-san/sre_test:master
        ports:
        - 80:80
    steps:
      - name: "Call API 1"
        uses: indiesdev/curl@v1.1
        id: api-get
        with:
          url: http://localhost:80/
          method: "GET"
          accept: 200
          log-response: true
      - name: "Call API 2"
        uses: indiesdev/curl@v1.1
        id: api2
        with:
          url: http://localhost:80/generate-passwords
          method: "POST"
          accept: 200
          body: '{ "min_length": 16, "special_chars": 1, "numbers": 1, "num_passwords": 1 }'
          log-response: true
